WHITESPACE = _{ " " | "\t" }

alpha = _{ 'a'..'z' | 'A'..'Z' }
digit = _{ '0'..'9' }
IDENT = @{ alpha ~ (alpha | digit)* }
NUMBER = @{ "-"? ~ digit+ ~ ("." ~ digit+)? }

PLUS = { "+" }
MINUS = { "-" }
MUL = { "*" }
DIV = { "/" }

symbol = { PLUS | MINUS | MUL | DIV }
atom = { (IDENT | NUMBER | symbol) }

term = {
    atom ~ term |
    atom
}

expression_item = {
    IDENT ~ "=" ~ term
}

expression = {
    expression_item ~ ("\n" ~ expression_item)*
}
