WHITESPACE = _{ " " | "\t" }

ALPHA = _{ 'a'..'z' | 'A'..'Z' }
DIGIT = _{ '0'..'9' }
IDENT = @{ ALPHA ~ (ALPHA | DIGIT)* }
NUMBER = @{ "-"? ~ DIGIT+ ~ ("." ~ DIGIT+)? }

PLUS = { "+" }
MINUS = { "-" }
MUL = { "*" }
DIV = { "/" }

symbol = { PLUS | MINUS | MUL | DIV }
atom = { IDENT | NUMBER | symbol }

term = {
    atom ~ term |
    atom
}

expression_item = {
    IDENT ~ "=" ~ term
}

expression = {
    expression_item ~ ("\n" ~ expression_item)*
}
